---
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create k8s pod for nginx
  kubernetes.core.k8s:
  state: present
  definition:
    apiVersion: v1
    metadata:
      name: "{{ app }}"
      namespace: "{{ namespace }}"
    spec:
      containers:
      - name: "{{ app }}"
        image: "{{ image }}"
        imagePullPolicy: Always

- name: Create a k8s service to expose nginx
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app }}"
        namespace: "{{ namespace }}"
      spec:
        selector:
          app: "{{ app }}"
        ports:
        - protocol: TCP
          targetPort: 8080
          name: port-8080-tcp
          port: 8080