---
- name: create infra
  hosts: localhost
  gather_facts: false
  environment:
    GOOGLE_CREDENTIALS: "{{ credentials_file }}"

  roles:
    - network
    - 
    # include comment for Ansible Lint test